#!/bin/bash

mkdir -p ~/.jupyter/custom
mv custom.js ~/.jupyter/custom/.

jupyter notebook --generate-config

mv jupyter_notebook_config.py ~/.jupyter/

mkdir -p ~/api
mv test.py ~/api/.
cd ~/api
touch __init__.py
cd ..
