#!/bin/bash

mkdir -p ~/.jupyter/custom
mv custom.js ~/.jupyter/custom/.

jupyter notebook --generate-config

mv jupyter_notebook_config.py ~/.jupyter/

mkdir -p ~/api
mv test.py ~/api/.
mv evaluate/ ~/api/.
mv assertion.py ~/api/.
touch ~/api/__init__.py
